pipeline {
    agent any
     parameters {
        booleanParam(name: 'CLSD_API_COMPATIBILITY_STEP_REQUIRED', defaultValue: false, description: 'Execute API/Contract Tests')
        booleanParam(name: 'CLSD_DB_ROLLBACK_STEP_REQUIRED', defaultValue: false, description: 'Test latest prod version against DB changes and dependecies')
        booleanParam(name: 'CLSD_DEPLOY_TO_TEST_STEP_REQUIRED', defaultValue: false, description: 'Deploy to Release')
        booleanParam(name: 'CLSD_PUBLISH_RELEASE', defaultValue: false, description: 'Publish Release Artifact to Maven Repo')
        booleanParam(name: 'CLSD_CODE_SCANS_REQUIRED', defaultValue: false, description: 'Execute Code Scans')
    }
     stages {
        stage('Initialize') {
            steps {
                echo 'setting...'   
                 bat 'set'
            }
        }
       stage('build') {
          steps {                                
             bat 'echo building....'
             bat 'gradle build'
               bat 'echo builded....'    
            
          }
       }
         stage ("invoking clsd pipeline") {
            steps {
                echo "clsddddddddddddddddddddddddddd"
               build job: "clsd/master",parameters: [[$class: 'StringParameterValue', name: 'API_COMPATIBILITY_STEP_REQUIRED', value: CLSD_API_COMPATIBILITY_STEP_REQUIRED], [$class: 'StringParameterValue', name: 'DB_ROLLBACK_STEP_REQUIRED', value: CLSD_DB_ROLLBACK_STEP_REQUIRED],[$class: 'StringParameterValue', name: 'DEPLOY_TO_TEST_STEP_REQUIRED', value: CLSD_DEPLOY_TO_TEST_STEP_REQUIRED],[$class: 'StringParameterValue', name: 'PUBLISH_RELEASE', value: CLSD_PUBLISH_RELEASE],[$class: 'StringParameterValue', name: 'CODE_SCANS_REQUIRED', value: CLSD_CODE_SCANS_REQUIRED]], propagate: true, wait: true
                
            }
        }
         stage ("invoking cdus pipeline") {
            steps {
                echo "cdussssssssssssssssssssssssss"
                 build job: "cdus/master", propagate: true, wait: true
            }
        }
         
          
    }
    post { 
        always { 
           
             echo 'Done!'
        }
    }
}
