pipeline {
    agent any
     stages {
        stage('Initialize') {
            steps {
                echo 'setting...'   
                 bat 'set'
            }
        }
       stage('build') {
          steps {                                
             bat 'echo building....'
             bat 'gradle build'
               bat 'echo builded....'    
            
          }
       }
         stage ("invoking clsd pipeline") {
            steps {
                echo "clsddddddddddddddddddddddddddd"
                build job: "clsd/master",parameters: [booleanParam(name: 'CODE_SCANS_REQUIRED', value: 'true')], propagate: true, wait: true
            }
        }
         stage ("invoking cdus pipeline") {
            steps {
                echo "cdussssssssssssssssssssssssss"
                 build job: "cdus/master", propagate: true, wait: true
            }
        }
         
          
    }
    post { 
        always { 
           
             echo 'Done!'
        }
    }
}
